[toolchain]

[features]
seeds = false
skip-lint = false

[test]
startup_wait = 10000

[programs.localnet]
token_22_staking = "7kLCzmB2pbs5wg8M1rw41ijnc2a6UyvwcCHjisqqWHWU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/coach/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
