[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token22_staking = "8T7PNRcydv3f5M63rk7PQcu5bz1a3s31MmbShywwwpeS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ixmorrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
